"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { heroSlides } from "@/lib/store";
export default function HeroSlider() {
  const [activeSlide, setActiveSlide] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActiveSlide((current) => (current + 1) % heroSlides.length), 4200); return () => window.clearInterval(timer); }, []);
  return <section className="relative mb-5 overflow-hidden border-b border-[#d9dfc7] lg:mb-8"><div className="flex transition-transform duration-700 ease-out" style={{ transform: `translateX(-${activeSlide * 100}%)` }}>{heroSlides.map((slide) => <a key={slide.title} href={slide.href} className={`relative grid w-full shrink-0 overflow-hidden bg-gradient-to-r ${slide.bg}`} aria-label={slide.title}><div className="mx-auto grid min-h-[360px] w-full max-w-[1880px] items-center gap-6 px-4 py-8 sm:px-6 lg:min-h-[520px] lg:grid-cols-[0.95fr_1.05fr] lg:px-12"><div className="relative z-10 max-w-2xl"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#857b4f]">{slide.eyebrow}</p><h1 className="mt-4 text-4xl font-black leading-none text-[#244f31] sm:text-6xl lg:text-7xl">{slide.title}</h1><p className="mt-5 max-w-xl text-base font-semibold leading-7 text-[#405642] sm:text-xl">{slide.copy}</p><span className="mt-7 inline-flex bg-[#2d6b3f] px-6 py-4 text-sm font-black uppercase tracking-[0.14em] text-white">{slide.cta}</span></div><div className="relative mx-auto flex w-full max-w-[640px] items-center justify-center"><div className="absolute inset-x-8 bottom-3 h-16 bg-[#9cad7e]/30 blur-2xl" /><Image src={slide.image} alt="" width={620} height={620} sizes="(min-width: 1024px) 50vw, 92vw" loading="eager" className="relative aspect-square max-h-[430px] w-full object-contain lg:max-h-[500px]" priority /></div></div></a>)}</div><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2">{heroSlides.map((slide, index) => <button key={slide.title} type="button" aria-label={`Show slide ${index + 1}`} className={`h-2.5 transition-all ${index === activeSlide ? "w-8 bg-[#2d6b3f]" : "w-2.5 bg-[#9bab7f]"}`} onClick={() => setActiveSlide(index)} />)}</div></section>;
}
